# Generated by Django 6.0.4 on 2026-04-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_alter_todo_options_todo_description_todo_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                choices=[("1", "Alta"), ("2", "Média"), ("3", "Baixa")],
                default="2",
                max_length=1,
                verbose_name="Prioridade",
            ),
        ),
    ]
